# Generated by Django 5.0.14 on 2026-06-22 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50, verbose_name='源类型')),
                ('source_id', models.IntegerField(verbose_name='源ID')),
                ('target_type', models.CharField(max_length=50, verbose_name='目标类型')),
                ('target_id', models.IntegerField(verbose_name='目标ID')),
                ('relation_type', models.CharField(choices=[('related', '相关'), ('prerequisite', '前置'), ('inspires', '启发'), ('contradicts', '矛盾'), ('custom', '自定义')], default='related', max_length=20, verbose_name='关系类型')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_edges', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关联边',
                'verbose_name_plural': '关联边',
                'db_table': 'actions_relation_edge',
                'indexes': [models.Index(fields=['user', 'source_type', 'source_id'], name='actions_rel_user_id_b14969_idx'), models.Index(fields=['user', 'target_type', 'target_id'], name='actions_rel_user_id_f71912_idx')],
            },
        ),
    ]
