# Generated by Django 5.0.14 on 2026-06-22 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationedge',
            constraint=models.UniqueConstraint(fields=('user', 'source_type', 'source_id', 'target_type', 'target_id', 'relation_type'), name='unique_relation_edge'),
        ),
    ]
