# Generated by Django 5.0.14 on 2026-06-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示 Tokens')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='生成 Tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总 Tokens')),
                ('cost', models.FloatField(default=0.0, verbose_name='费用')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM 调用日志',
                'verbose_name_plural': 'LLM 调用日志',
                'db_table': 'llm_call_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
