# Generated by Django 5.0.14 on 2026-06-14 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_summary', models.TextField(blank=True, verbose_name='画像摘要')),
                ('facts', models.JSONField(blank=True, default=list, verbose_name='用户事实')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='兴趣标签')),
                ('version', models.IntegerField(default=0, verbose_name='画像版本')),
                ('last_built_at', models.DateTimeField(blank=True, null=True, verbose_name='最后构建时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户画像',
                'verbose_name_plural': '用户画像',
                'db_table': 'llm_user_persona',
            },
        ),
    ]
