# Generated by Django 5.0.14 on 2026-06-14 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_userpersona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Core Profile'), (2, 'Context'), (3, 'Detail')], verbose_name='记忆级别')),
                ('memory_type', models.CharField(choices=[('persona_summary', '画像摘要'), ('user_fact', '用户事实'), ('interest', '兴趣标签'), ('goal', '学习目标'), ('skill_progress', '技能进度'), ('conversation', '对话记录'), ('insight', '学习洞察'), ('wellness', '身心健康')], max_length=30, verbose_name='记忆类型')),
                ('content', models.TextField(verbose_name='记忆内容')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重(0-10)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('accessed_at', models.DateTimeField(auto_now=True, verbose_name='最后访问')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '记忆条目',
                'verbose_name_plural': '记忆条目',
                'db_table': 'llm_memory_entry',
                'ordering': ['-weight', '-created_at'],
                'indexes': [models.Index(fields=['user', 'level'], name='mem_user_level'), models.Index(fields=['user', 'memory_type'], name='mem_user_type'), models.Index(fields=['user', 'is_active'], name='mem_user_active'), models.Index(fields=['expires_at'], name='mem_expires')],
            },
        ),
    ]
