# Generated by Django 5.0.14 on 2026-06-21 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_memoryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('alert', 'Goal Alert'), ('suggestion', 'Smart Suggestion'), ('reminder', 'Memory Reminder'), ('briefing', 'Morning Briefing'), ('summary', 'Evening Summary')], max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'P1 - Alert'), (2, 'P2 - Suggestion'), (3, 'P3 - Reminder'), (4, 'P4 - Briefing'), (5, 'P5 - Summary')], default=5)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shown', 'Shown'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surface_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_surface_event',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='llm_surface_user_id_1899b8_idx'), models.Index(fields=['user', 'event_type'], name='llm_surface_user_id_26e2c4_idx')],
            },
        ),
    ]
