# Generated by Django 5.0.14 on 2026-06-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_surfaceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersona',
            name='last_signal_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后信号时间'),
        ),
        migrations.AlterField(
            model_name='memoryentry',
            name='memory_type',
            field=models.CharField(choices=[('persona_summary', '画像摘要'), ('user_fact', '用户事实'), ('interest', '兴趣标签'), ('goal', '学习目标'), ('skill_progress', '技能进度'), ('conversation', '对话记录'), ('insight', '学习洞察'), ('wellness', '身心健康'), ('persona_history', '画像历史')], max_length=30, verbose_name='记忆类型'),
        ),
    ]
