# Generated by Django 5.0.14 on 2026-06-23 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_userpersona_last_signal_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surfaceevent',
            name='body',
        ),
        migrations.AddField(
            model_name='surfaceevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='surfaceevent',
            name='event_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='事件去重键'),
        ),
        migrations.AddField(
            model_name='surfaceevent',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='源ID'),
        ),
        migrations.AddField(
            model_name='surfaceevent',
            name='source_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='源类型'),
        ),
        migrations.AlterField(
            model_name='surfaceevent',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('read', '已读'), ('acted', '已操作'), ('dismissed', '已忽略'), ('archived', '已归档')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='surfaceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key__gt', '')), fields=('user', 'event_key'), name='unique_surface_event_key'),
        ),
    ]
