# Generated by Django 5.0.14 on 2026-06-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritecreator',
            unique_together={('user', 'name', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='monitortopic',
            unique_together={('user', 'keyword')},
        ),
    ]
