# Generated by Django 5.0.14 on 2026-06-07 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='创作者名称')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('homepage_url', models.URLField(max_length=500, unique=True, verbose_name='主页 URL')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='头像 URL')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '创作者',
                'verbose_name_plural': '创作者',
                'db_table': 'content_creator',
            },
        ),
        migrations.CreateModel(
            name='RawContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000, unique=True, verbose_name='来源 URL')),
                ('raw_data', models.JSONField(default=dict, verbose_name='原始数据')),
                ('raw_html', models.TextField(blank=True, verbose_name='原始 HTML')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': '原始内容',
                'verbose_name_plural': '原始内容',
                'db_table': 'content_raw',
            },
        ),
        migrations.CreateModel(
            name='ProcessedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('url', models.URLField(blank=True, default='', max_length=1000, verbose_name='内容 URL')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI 摘要')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='质量评分')),
                ('stage', models.CharField(choices=[('pending', '待处理'), ('active', '活跃'), ('cooling', '冷却'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='阶段')),
                ('content_type', models.CharField(choices=[('video', '视频'), ('article', '文章'), ('podcast', '播客')], max_length=20, verbose_name='内容类型')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.creator')),
                ('raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed', to='content.rawcontent')),
            ],
            options={
                'verbose_name': '处理内容',
                'verbose_name_plural': '处理内容',
                'db_table': 'content_processed',
            },
        ),
        migrations.CreateModel(
            name='ContentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(verbose_name='嵌入向量')),
                ('model_name', models.CharField(default='bge-small-zh-v1.5', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='content.processedcontent')),
            ],
            options={
                'verbose_name': '内容向量',
                'verbose_name_plural': '内容向量',
                'db_table': 'content_embedding',
            },
        ),
        migrations.AddIndex(
            model_name='processedcontent',
            index=models.Index(fields=['stage'], name='content_pro_stage_fe3810_idx'),
        ),
        migrations.AddIndex(
            model_name='processedcontent',
            index=models.Index(fields=['quality_score'], name='content_pro_quality_b46bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='processedcontent',
            index=models.Index(fields=['-published_at'], name='content_pro_publish_070fdd_idx'),
        ),
    ]
