# Generated by Django 5.0.14 on 2026-06-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVector',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='content.processedcontent', verbose_name='内容')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='嵌入向量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '内容向量',
                'verbose_name_plural': '内容向量',
                'db_table': 'content_vector',
            },
        ),
    ]
