# Generated by Django 5.0.14 on 2026-06-16 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmittedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='来源 URL')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='标题')),
                ('body_text', models.TextField(blank=True, verbose_name='正文')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
            options={
                'verbose_name': '用户提交内容',
                'verbose_name_plural': '用户提交内容',
                'db_table': 'content_user_submitted',
                'ordering': ['-created_at'],
            },
        ),
    ]
