# Generated by Django 5.0.14 on 2026-06-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_user_submitted_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentvector',
            name='embedding_status',
            field=models.CharField(choices=[('pending', '未生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='pending', max_length=20, verbose_name='嵌入状态'),
        ),
    ]
