# Generated by Django 5.0.14 on 2026-06-07 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(choices=[(1, '很差'), (2, '较差'), (3, '一般'), (4, '良好'), (5, '很好')], verbose_name='心情评分')),
                ('sleep_hours', models.FloatField(blank=True, null=True, verbose_name='睡眠时长')),
                ('exercise_minutes', models.IntegerField(blank=True, null=True, verbose_name='运动时长(分钟)')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('record_date', models.DateField(auto_now_add=True, verbose_name='记录日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '身心健康记录',
                'verbose_name_plural': '身心健康记录',
                'db_table': 'wellness_record',
                'ordering': ['-record_date'],
            },
        ),
    ]
