# Generated by Django 5.0.14 on 2026-06-11 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('break', '休息'), ('eye', '护眼'), ('posture', '坐姿'), ('exercise', '运动'), ('sleep', '睡眠')], max_length=20, verbose_name='建议类型')),
                ('content', models.TextField(verbose_name='建议内容')),
                ('trigger_reason', models.CharField(max_length=100, verbose_name='触发原因')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '健康建议',
                'verbose_name_plural': '健康建议',
                'db_table': 'wellness_suggestion',
                'ordering': ['-created_at'],
            },
        ),
    ]
