# Generated by Django 5.0.14 on 2026-06-12 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_healthsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='healthsuggestion',
            index=models.Index(fields=['user', 'is_read'], name='wellness_suggestion_user_read'),
        ),
        migrations.AddIndex(
            model_name='wellnessrecord',
            index=models.Index(fields=['user', 'record_date'], name='wellness_record_user_date'),
        ),
    ]
