import os
os.chdir(r"D:\Jarvis project")

header = '<!DOCTYPE html>\n<html lang="zh-CN" data-theme="jarvis">\n<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">\n<script src="https://cdn.tailwindcss.com"></script>\n<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">\n<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">\n'
style = '<style>:root{--surface-bg:#08080D;--surface-card:rgba(20,20,30,0.65);--primary:#8B5CF6;--secondary:#4F8CFF;--accent:#06B6D4;--text-main:#F1F1F6;--text-secondary:#9191A8}[data-theme="ocean"]{--primary:#2563EB;--secondary:#06B6D4;--accent:#67E8F9}[data-theme="sunset"]{--primary:#F97316;--secondary:#EC4899;--accent:#FACC15}[data-theme="forest"]{--primary:#22C55E;--secondary:#14B8A6;--accent:#84CC16}[data-theme="rose"]{--primary:#EC4899;--secondary:#8B5CF6;--accent:#F472B6}\nbody{background:var(--surface-bg);color:var(--text-main);font-family:"Inter",sans-serif;margin:0;overflow:hidden}\nbody::before{content:"";position:fixed;top:-30%;left:-30%;width:160%;height:160%;pointer-events:none;background:radial-gradient(circle at 20%20%,color-mix(in srgb,var(--primary)30%,transparent),transparent 35%),radial-gradient(circle at 80%25%,color-mix(in srgb,var(--secondary)20%,transparent),transparent 35%),radial-gradient(circle at 60%80%,color-mix(in srgb,var(--accent)15%,transparent),transparent 40%);filter:blur(120px);animation:aurora-drift 30s ease-in-out infinite;z-index:-3}\n@keyframes aurora-drift{0%,100%{transform:translate(0,0)scale(1)}50%{transform:translate(5%,-5%)scale(1.1)}}\n.glass-card{background:linear-gradient(135deg,rgba(255,255,255,.05),rgba(255,255,255,.015));backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.06);transition:all .3s ease}\n.glass-card:hover{transform:translateY(-4px);border-color:color-mix(in srgb,var(--primary)40%,transparent);box-shadow:0 0 25px color-mix(in srgb,var(--primary)10%,transparent)}\n.nav-active{background:rgba(255,255,255,0.08);color:white!important;position:relative}\n.nav-active::before{content:"";position:absolute;left:0;top:50%;transform:translateY(-50%);width:3px;height:18px;background:var(--primary);box-shadow:0 0 10px var(--primary);border-radius:0 4px 4px 0}\nh1,h2,h3,h4{font-family:"Space Grotesk",sans-serif}\n.no-scrollbar::-webkit-scrollbar{display:none}</style>\n</head>\n'
sidebar = '<body class="flex h-screen">\n<aside class="w-64 bg-black/30 backdrop-blur-3xl border-r border-white/5 flex flex-col z-20"><div class="p-8"><h1 class="text-2xl font-bold italic text-white tracking-tighter">JARVIS</h1></div>\n<nav class="flex-1 px-4 space-y-2">\n<a href="/" class="flex items-center gap-3 px-4 py-3 rounded-2xl text-[#9191A8] hover:bg-white/5 transition"><i class="bi bi-grid-fill"></i> Dashboard</a>\n<a href="/chat/" class="flex items-center gap-3 px-4 py-3 rounded-2xl text-[#9191A8] hover:bg-white/5 transition"><i class="bi bi-stars"></i> Agent</a>\n<a href="/memory/timeline/" class="flex items-center gap-3 px-4 py-3 rounded-2xl text-[#9191A8] hover:bg-white/5 transition"><i class="bi bi-brain"></i> Memory</a>\n<a href="/goals/" class="flex items-center gap-3 px-4 py-3 rounded-2xl text-[#9191A8] hover:bg-white/5 transition"><i class="bi bi-target"></i> Goals</a>\n<a href="/wellness/suggestions/" class="flex items-center gap-3 px-4 py-3 rounded-2xl text-[#9191A8] hover:bg-white/5 transition"><i class="bi bi-heart"></i> Wellness</a>\n</nav><div class="h-px bg-white/5 mx-4 my-2"></div>\n<nav class="px-4 space-y-2">\n<a href="/content/feed/" class="flex items-center gap-3 px-4 py-3 rounded-2xl text-[#9191A8] hover:bg-white/5 transition"><i class="bi bi-book"></i> Content</a>\n<a href="/trajectory/skills/" class="flex items-center gap-3 px-4 py-3 rounded-2xl nav-active"><i class="bi bi-diagram-3" style="color:var(--primary)"></i> Trajectory</a>\n</nav><div class="h-px bg-white/5 mx-4 my-2"></div>\n<nav class="px-4 space-y-2"><a href="/profile/" class="flex items-center gap-3 px-4 py-3 rounded-2xl text-[#9191A8] hover:bg-white/5 transition"><i class="bi bi-gear"></i> Settings</a></nav>\n<div class="p-6 border-t border-white/5 flex items-center gap-3"><div class="w-8 h-8 rounded-full bg-zinc-800 border border-white/10"></div><span class="text-xs text-[#C8C8D8] font-medium">{{ user.username|default:"Alex" }} OS</span></div>\n</aside>\n'
theme_js = '<script>var switcher=document.getElementById("themeSwitcher");function applyTheme(t){document.documentElement.setAttribute("data-theme",t);localStorage.setItem("jarvis-theme",t)}if(switcher){switcher.addEventListener("change",function(e){applyTheme(e.target.value)});window.addEventListener("DOMContentLoaded",function(){var saved=localStorage.getItem("jarvis-theme")||"jarvis";applyTheme(saved);switcher.value=saved})}</script>\n</body></html>'

# path_detail specific content
detail_body = '''<main class="flex-1 flex flex-col relative z-10 overflow-hidden">
<header class="h-20 flex items-center justify-between px-10 border-b border-white/5 bg-black/10 backdrop-blur-xl">
<div class="flex items-center gap-4"><a href="/trajectory/paths/" class="text-xs hover:underline" style="color:#9191A8;">\u2190 \u8def\u5f84\u5217\u8868</a><div class="h-4 w-px bg-white/10"></div><h2 class="text-xl font-bold text-white tracking-tight">{{ path.title|truncatechars:30 }}</h2></div>
<div class="flex items-center gap-6"><div class="flex items-center gap-2"><i class="bi bi-palette2 text-xs text-[#9191A8]"></i><select id="themeSwitcher" class="bg-white/5 border border-white/10 rounded-lg px-3 py-1.5 text-[10px] text-white outline-none cursor-pointer focus:border-[var(--primary)] transition"><option value="jarvis">Jarvis</option><option value="ocean">Ocean</option><option value="sunset">Sunset</option><option value="forest">Forest</option><option value="rose">Rose</option></select></div></div>
</header>
<div class="flex-1 overflow-y-auto p-10 no-scrollbar"><div class="max-w-4xl mx-auto">
<div class="glass-card p-8 rounded-[2.5rem] mb-8"><div class="flex items-center justify-between mb-4"><h1 class="text-xl font-bold">{{ path.title }}</h1><span class="text-[10px] font-bold px-3 py-1 rounded-full" style="background:color-mix(in srgb,var(--primary)15%,transparent);color:var(--primary);">{{ completed }}/{{ total }}</span></div>
{% if path.goal_description %}<p class="text-sm mb-4" style="color:#9191A8;">{{ path.goal_description }}</p>{% endif %}
<div class="h-1.5 w-full bg-white/5 rounded-full overflow-hidden"><div class="h-full rounded-full" style="width:{{ progress_pct }}%;background:var(--primary)"></div></div>
<p class="text-xs mt-2" style="color:#5C5C72;">{{ progress_pct }}% \u5b8c\u6210</p></div>
{% if nodes %}<div class="space-y-4">{% for node in nodes %}<div class="glass-card p-5 rounded-[2rem] flex items-center justify-between{% if node.status == 'completed' %} opacity-60{% endif %}">
<div class="flex items-center gap-4"><div class="w-8 h-8 rounded-xl flex items-center justify-center text-sm{% if node.status == 'completed' %} bg-[#22C55E]/10 text-[#22C55E]{% elif node.status == 'in_progress' %} bg-[var(--primary)]/10 text-[var(--primary)]{% else %} bg-white/5 text-[#5C5C72]{% endif %}">{% if node.status == 'completed' %}<i class="bi bi-check-lg"></i>{% else %}{{ node.order }}{% endif %}</div>
<div><p class="text-sm font-medium">{% if node.skill %}{{ node.skill.name }}{% else %}\u8282\u70b9 {{ node.order }}{% endif %}</p>{% if node.estimated_minutes %}<p class="text-[10px]" style="color:#5C5C72;">\u9884\u8ba1 {{ node.estimated_minutes }} \u5206\u949f</p>{% endif %}</div></div>
<div><span class="text-[10px] px-2 py-0.5 rounded-full" style="background:rgba(255,255,255,0.03);color:#5C5C72;">{{ node.get_status_display }}</span></div>
</div>{% endfor %}</div>{% else %}<p class="text-center py-8 text-xs" style="color:#5C5C72;">\u6b64\u8def\u5f84\u6682\u65e0\u8282\u70b9</p>{% endif %}
</div></div></main>'''

content = header + '<title>Jarvis OS - Path Detail</title>\n' + style + sidebar + detail_body + theme_js
with open("templates/trajectory/path_detail.html", "w", encoding="utf-8") as f:
    f.write(content)
print("path_detail.html written")
