# Generated by Django 5.0.14 on 2026-06-23 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('goal', 'Goal'), ('skill', 'Skill'), ('interest', 'Interest'), ('memory', 'Memory')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('importance', models.FloatField(default=1.0)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Graph Node',
                'db_table': 'graph_node',
                'indexes': [models.Index(fields=['user', 'node_type'], name='graph_node_user_id_f7d810_idx')],
            },
        ),
    ]
