# Generated by Django 5.0.14 on 2026-06-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200, verbose_name='事件类型')),
                ('payload', models.JSONField(default=dict, verbose_name='事件数据')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
                'db_table': 'eventbus_event',
                'indexes': [models.Index(fields=['status'], name='eventbus_ev_status_f83d64_idx'), models.Index(fields=['event_type'], name='eventbus_ev_event_t_6a391f_idx')],
            },
        ),
    ]
