# Generated by Django 5.0.14 on 2026-06-07 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='目标标题')),
                ('description', models.TextField(blank=True, verbose_name='目标描述')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('abandoned', '已放弃')], default='active', max_length=20, verbose_name='状态')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习目标',
                'verbose_name_plural': '学习目标',
                'db_table': 'goals_goal',
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.FloatField(default=0.0, verbose_name='进度百分比')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='goals.goal')),
            ],
            options={
                'verbose_name': '目标进度',
                'verbose_name_plural': '目标进度',
                'db_table': 'goals_progress',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
