# Generated by Django 5.0.14 on 2026-06-11 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentvector'),
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at'], 'verbose_name': '学习目标', 'verbose_name_plural': '学习目标'},
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月'), ('quarterly', '季度')], default='daily', max_length=10, verbose_name='周期类别'),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('custom', '自定义'), ('reading', '阅读'), ('coding', '编码练习'), ('study', '学习'), ('project', '项目')], default='custom', max_length=20, verbose_name='目标类型'),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='是否循环'),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='目标单位'),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.FloatField(blank=True, null=True, verbose_name='目标值'),
        ),
        migrations.CreateModel(
            name='GoalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='记录日期')),
                ('duration_minutes', models.IntegerField(verbose_name='学习时长(分钟)')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('content_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.processedcontent', verbose_name='关联内容')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.goal', verbose_name='关联目标')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'db_table': 'goals_session',
                'ordering': ['-date'],
            },
        ),
    ]
