# Generated by Django 5.0.14 on 2026-06-12 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentvector'),
        ('goals', '0002_alter_goal_options_goal_category_goal_goal_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goals_goal_user_status'),
        ),
        migrations.AddIndex(
            model_name='goalsession',
            index=models.Index(fields=['user', 'date'], name='goals_session_user_date'),
        ),
    ]
